/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.github.cloudiator.rest.api;

import io.github.cloudiator.rest.model.InstallationRequest;
import io.github.cloudiator.rest.model.OclSolution;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

@Api(value = "installer", description = "the installer API")
public interface InstallerApi {

    @ApiOperation(value = "", notes = "Installs Cloudiator tools on provided node", response = OclSolution.class, tags={ "misc", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = OclSolution.class) })
    
    @RequestMapping(value = "/installer",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<OclSolution> installTools(@ApiParam(value = "a request to install the cloudiator tools on a provided node" ,required=true )  @Valid @RequestBody InstallationRequest installRequest);

}
