/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.github.cloudiator.rest.api;

import io.github.cloudiator.rest.model.OclProblem;
import io.github.cloudiator.rest.model.OclSolution;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "ocl", description = "the ocl API")
public interface OclApi {

    @ApiOperation(value = "", nickname = "solveOCL", notes = "Solves an Ocl Problem", response = OclSolution.class, authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "misc", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = OclSolution.class) })
    @RequestMapping(value = "/ocl",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<OclSolution> solveOCL(@ApiParam(value = "OCL Problem to solve" ,required=true )  @Valid @RequestBody OclProblem oclProblem);

}
