/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.github.cloudiator.rest.api;

import io.github.cloudiator.rest.model.Schedule;
import io.github.cloudiator.rest.model.ScheduleNew;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "schedule", description = "the schedule API")
public interface ScheduleApi {

    @ApiOperation(value = "", nickname = "addSchedule", notes = "Creates a new schedule ", response = Schedule.class, authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "job", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK ", response = Schedule.class) })
    @RequestMapping(value = "/schedule",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Schedule> addSchedule(@ApiParam(value = "Schedule to be created " ,required=true )  @Valid @RequestBody ScheduleNew schedule);


    @ApiOperation(value = "", nickname = "getSchedules", notes = "Retrieves all schedules by the current user. ", response = Schedule.class, responseContainer = "List", authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "job", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Schedule.class, responseContainer = "List") })
    @RequestMapping(value = "/schedule",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Schedule>> getSchedules();

}
