/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.github.cloudiator.rest.api;

import io.github.cloudiator.rest.model.NodeCandidate;
import io.github.cloudiator.rest.model.NodeRequirements;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "matchmaking", description = "the matchmaking API")
public interface MatchmakingApi {

    @ApiOperation(value = "", nickname = "solveMatchmaking", notes = "Solves a matchmaking problem", response = NodeCandidate.class, responseContainer = "List", authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "matchmaking", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = NodeCandidate.class, responseContainer = "List") })
    @RequestMapping(value = "/matchmaking",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<List<NodeCandidate>> solveMatchmaking(@ApiParam(value = "The requirements with respect to nodes" ,required=true )  @Valid @RequestBody NodeRequirements nodeRequirements);

}
