/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.github.cloudiator.rest.api;

import java.util.List;
import io.github.cloudiator.rest.model.NodeCandidate;
import io.github.cloudiator.rest.model.Requirement;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "nodeCandidates", description = "the nodeCandidates API")
public interface NodeCandidatesApi {

    @ApiOperation(value = "", nickname = "findNodeCandidates", notes = "Returns possible node candidates. ", response = NodeCandidate.class, responseContainer = "List", authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "matchmaking", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "ACCEPTED", response = NodeCandidate.class, responseContainer = "List") })
    @RequestMapping(value = "/nodeCandidates",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<List<NodeCandidate>> findNodeCandidates(@ApiParam(value = "Node Request "  )  @Valid @RequestBody List<Requirement> nodeRequirements);


    @ApiOperation(value = "", nickname = "getNodeCanidate", notes = "Returns the node candidate with the given id if it exists. ", response = NodeCandidate.class, authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "matchmaking", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The node candidate identified with the id ", response = NodeCandidate.class) })
    @RequestMapping(value = "/nodeCandidates/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<NodeCandidate> getNodeCandidate(@ApiParam(value = "Unique identifier of the resource",required=true) @PathVariable("id") String id);

}
