/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.github.cloudiator.rest.api;

import java.util.List;
import io.github.cloudiator.rest.model.NodeCandidate;
import io.github.cloudiator.rest.model.Requirement;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@Api(value = "nodeCandidates", description = "the nodeCandidates API")
public interface NodeCandidatesApi {

    @ApiOperation(value = "", nickname = "findNodeCandidates", notes = "Returns possible node candidates. ", response = NodeCandidate.class, responseContainer = "List", authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "matchmaking", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "ACCEPTED", response = NodeCandidate.class, responseContainer = "List") })
    @RequestMapping(value = "/nodeCandidates",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<List<NodeCandidate>> findNodeCandidates(@ApiParam(value = "Node Request "  )  @Valid @RequestBody List<Requirement> nodeRequirements);

}
