/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.github.cloudiator.rest.api;

import io.github.cloudiator.rest.model.Queue;
import io.github.cloudiator.rest.model.Schedule;
import io.github.cloudiator.rest.model.ScheduleNew;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "schedule", description = "the schedule API")
public interface ScheduleApi {

    @ApiOperation(value = "", nickname = "addSchedule", notes = "Creates a new schedule ", response = Queue.class, authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "process", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "ACCEPTED", response = Queue.class) })
    @RequestMapping(value = "/schedule",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Queue> addSchedule(@ApiParam(value = "Schedule to be created " ,required=true )  @Valid @RequestBody ScheduleNew schedule);


    @ApiOperation(value = "", nickname = "deleteSchedule", notes = "Deletes the schedule identified by the given id and all corresponding processes and nodes. ", response = Queue.class, authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "process", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "ACCEPTED", response = Queue.class) })
    @RequestMapping(value = "/schedule/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Queue> deleteSchedule(@ApiParam(value = "Unique identifier of the resource",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "findSchedule", notes = "Retrieves the schedule identified by parameter id. ", response = Schedule.class, authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "process", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Schedule.class) })
    @RequestMapping(value = "/schedule/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Schedule> findSchedule(@ApiParam(value = "Unique identifier of the resource",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "getSchedules", notes = "Retrieves all schedules by the current user. ", response = Schedule.class, responseContainer = "List", authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "process", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Schedule.class, responseContainer = "List") })
    @RequestMapping(value = "/schedule",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Schedule>> getSchedules();


    @ApiOperation(value = "", nickname = "scheduleGraph", notes = "Returns a json graph representation usable by cyctoscape.js ", response = Object.class, authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "process", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "See js.cyctoscape.org ", response = Object.class) })
    @RequestMapping(value = "/schedule/{id}/graph",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> scheduleGraph(@ApiParam(value = "Unique identifier of the resource",required=true) @PathVariable("id") String id);

}
