/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.github.cloudiator.rest.api;

import io.github.cloudiator.rest.model.Solution;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "solution", description = "the solution API")
public interface SolutionApi {

    @ApiOperation(value = "", nickname = "getSolution", notes = "Returns a solution of the matchmaking process (if it is still available) ", response = Solution.class, authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "matchmaking", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The solution identified with the id ", response = Solution.class) })
    @RequestMapping(value = "/solution/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Solution> getSolution(@ApiParam(value = "Unique identifier of the resource",required=true) @PathVariable("id") String id);

}
