/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.github.cloudiator.rest.api;

import io.github.cloudiator.rest.model.Tenant;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@Api(value = "tenants", description = "the tenants API")
public interface TenantsApi {

    @ApiOperation(value = "", nickname = "createTenant", notes = "Creates a new tenant ", response = Tenant.class, authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "user", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Tenant.class) })
    @RequestMapping(value = "/tenants",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Tenant> createTenant(@ApiParam(value = "Tenant creation request "  )  @Valid @RequestBody Tenant tenant);

}
